apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: nginx
    newName: nginx
    newTag: 1.23.2-alpine
  - name: cv
    newName: digitalacademydevops/cv
    newTag: main

resources:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: cv-mostashkin
  spec:
    rules:
      - host: mostashkin.dactusur.ru
